# This is a basic workflow to help you get started with Actions

name: pypi_publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 运行单元测试的 Job
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'

      - name: Install dependencies
        run: pdm install  # 使用 PDM 安装依赖

      - name: Run unit tests
        run: pdm run -v pytest tests

  # This workflow contains a single job called "build"
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    needs: test
    permissions:
      # 这个权限是为了私有仓库。
      contents: read
      # 重要提示：这个权限对于可信发布是必需的。
      id-token: write
    environment: pypi_publish  # 与 PyPI 上的环境名称一致
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4

      - name: Publish package distributions to PyPI
        run: pdm publish

      - name: Extract version from pyproject.toml
        id: extract_version
        run: |
          python -c "
          import tomli
          with open('pyproject.toml', 'rb') as f:
              print(tomli.load(f)['project']['version'])
          " > version.txt
      - name: Read version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: Verify PyPI upload
        run: pip install pyrunjs==$VERSION
